version: '2.2'
services:
 user-app:
  image: user-app
  build: MovieCruiserAuthenticationService/
  restart: always
  network_mode: host
  ports:
   - 2213:2213
  expose: 
   - 2213
  depends_on:
  - movie-mysql
  
   
 movie-app:
  image: image-app
  build: MovieCruiserService/
  restart: always
  network_mode: host
  depends_on:
   - movie-mysql
  ports:
   - 2212:2212
  expose:
  - 2212
  depends_on:
  - movie-mysql
 
 movie-mysql:
  image: mysql:5.5
  ports:
   - 3306:3306
  network_mode: host
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: moviedb
   MYSQL_USER: app_root
   MYSQL_PASSWORD: root123
   
 angular:
  image: angular-app
  build: frontend/
  network_mode: host
  container_name: angular-docker
  ports:
   - 4200:4200
